export const iconConfig = [
    { type: 'pdf', name: 'fa-solid:file-pdf', color: '#FF5924' },
    { type: 'doc', name: 'fa-solid:file-word', color: '#3560fc' },
    { type: 'docx', name: 'fa-solid:file-word', color: '#3560fc' },
    { type: 'ppt', name: 'ant-design:file-ppt-filled', color: '#FF5924' },
    { type: 'pptx', name: 'ant-design:file-ppt-filled', color: '#FF5924' },
    { type: 'txt', name: 'bxs:file-txt', color: '#65789B' },
    { type: 'csv', name: 'fa-solid:file-csv', color: '#00E079' },
    { type: 'xlsx', name: 'fa-solid:file-excel', color: '#00E079' },
    { type: 'xls', name: 'fa-solid:file-excel', color: '#00E079' },
    { type: 'md', name: 'ant-design:file-markdown-filled', color: '#13F1FF' },
    { type: 'png', name: 'tabler:photo-filled', color: '#13F1FF' },
    { type: 'jpg', name: 'tabler:photo-filled', color: '#13F1FF' },
    { type: 'jpeg', name: 'tabler:photo-filled', color: '#13F1FF' },
];